on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  setup_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with: 
          node-version: ${{inputs.node-version}}
      - run: npm install
        
      
